#include <iostream>

void Gameloop() {
	//EL juego se tiene que correr hasta que el usuario lo pare
	// Bienvenido a PAPERS PLEASE
	//1 - JUGAR
	//2 - SALIR
	//
	//....
	// LIST<PERSON> LISTADEPERSONAS;
	// LISTA DE PERSONAS.PUSH_FRONT(P1,P2,P3,...)
	// 
	// WHILE(LISTA DE PERSONAS != LISTA.END)
	// {
	//SE ACERCA LA PRIMER PERSONA

	//**LE ENTREGAN LOS DOCUMENTOS
	//CLS
	// MOSTRAR ID Y PASAPORTE DE LA PRIMERA PERSONA
	// PUEDEN ESTAR CORRECTOS O INCORRECTOS
	// 
	//PASA? O NO PASA?[Y/N]
	//SI VALIDATE_PERSON() == RESPUESTA DEL USUARIO
	//CONTADOR DE PUNTOS USUARIO ++
	//ELSE CONTADOR DE PUNTOS USUARIO --
	//}


}
